# -------------------------------------------------------------------
# Use `<prefix> + r` to reload tmux conf
# -------------------------------------------------------------------
unbind r
bind r source-file ~/.tmux.conf


# -------------------------------------------------------------------
# Change <prefix> to Ctrl + Space
# -------------------------------------------------------------------
# this makes it easier to work across keyboards with different layouts
unbind C-b
unbind C-space
set -g prefix C-space
bind C-space send-prefix


# -------------------------------------------------------------------
# Start windows and panes at 1, not 0
# -------------------------------------------------------------------
set -g base-index 1
setw -g pane-base-index 1

# -------------------------------------------------------------------
# Enable mouse support
# -------------------------------------------------------------------
set -g mouse on


# -------------------------------------------------------------------
# Change window splits shortcuts
# -------------------------------------------------------------------
# h: horizontal
# v: vertical
# these are better mnemonics
unbind %
unbind '"'

bind h split-window -h -c "#{pane_current_path}"
bind v split-window -v -c "#{pane_current_path}"


# -------------------------------------------------------------------
# Move status bar to the top
# -------------------------------------------------------------------
set-option -g status-position top


# -------------------------------------------------------------------
# TPM setup
# -------------------------------------------------------------------

# -----
# List of plugins
# -----
set -g @plugin 'tmux-plugins/tpm'
set -g @plugin 'tmux-plugins/tmux-cpu'
set -g @plugin 'tmux-plugins/tmux-battery'
#set -g @plugin 'tmux-plugins/tmux-resurrect'

# -----
# catppuccin/tmux configuration
# -----
set -g @plugin 'catppuccin/tmux'

set -g @catppuccin_flavor "mocha"
set -g @catppuccin_window_status_style "rounded"
set -g @catppuccin_window_flags "icon" # none, icon, or text
set -g @catppuccin_window_number_position "right"
set -g @catppuccin_window_current_text "#W"
set -g @catppuccin_window_text "#W"

# Load catppuccin
run ~/.tmux/plugins/tmux/catppuccin.tmux

# Make the status line pretty and add some modules
set -g status-right-length 100
set -g status-left-length 100
set -g status-left "#{E:@catppuccin_status_session}"
set -agF status-right "#{E:@catppuccin_status_cpu}"
set -agF status-right "#{E:@catppuccin_status_ram}"
set -ag status-right "#{E:@catppuccin_status_uptime}"
set -agF status-right "#{E:@catppuccin_status_battery}"


# Initialize TMUX plugin manager (keep this line at the very bottom of tmux.conf
run '~/.tmux/plugins/tpm/tpm'
